import type { Host, Review, Experience, HostApplication } from '@/lib/types';

export const hosts: Host[] = [
  {
    id: 'host-1',
    name: 'Maria',
    avatarImageId: 'host-1',
    bio: 'Passionate Italian home cook, sharing my grandmother\'s recipes with the world. I love opera, fresh pasta, and good conversation.',
    languages: ['Italian', 'English'],
    culture: 'Italian',
    hostingStyle: ['Family-style meals', 'Storytelling & conversation'],
  },
  {
    id: 'host-2',
    name: 'Kenji',
    avatarImageId: 'host-2',
    bio: 'I am a designer and a foodie from Tokyo. Join me for a quiet, traditional meal where we can appreciate the beauty of simplicity in Japanese cuisine.',
    languages: ['Japanese', 'English'],
    culture: 'Japanese',
    hostingStyle: ['Quiet & traditional'],
  },
  {
    id: 'host-3',
    name: 'Priya',
    avatarImageId: 'host-3',
    bio: 'My family and I love to host! We fill our home with the aromas of South Indian spices and the sounds of laughter. Come as a guest, leave as family.',
    languages: ['Tamil', 'English'],
    culture: 'South Indian',
    hostingStyle: ['Festive & social', 'Family-style meals'],
  },
  {
    id: 'host-4',
    name: 'Javier',
    avatarImageId: 'host-4',
    bio: 'From Oaxaca with love. I bring the vibrant street food culture of Mexico to my home. Expect bold flavors, lots of color, and great stories.',
    languages: ['Spanish', 'English'],
    culture: 'Mexican',
    hostingStyle: ['Festive & social', 'Storytelling & conversation'],
  },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    author: { name: 'Sophie', avatarImageId: 'host-4' },
    rating: 5,
    comment: 'An absolutely unforgettable evening! Maria\'s pasta was the best I\'ve ever had, and her stories made the experience so special. Felt like dinner with family.',
    date: '2023-10-15',
  },
  {
    id: 'review-2',
    author: { name: 'David', avatarImageId: 'host-2' },
    rating: 4.5,
    comment: 'The food was incredible, and the atmosphere was so peaceful. A truly authentic and meditative dining experience. Highly recommended.',
    date: '2023-10-12',
  },
];

export const experiences: Experience[] = [
  {
    id: '1',
    title: 'Nonna\'s Roman Pasta Feast',
    host: hosts[0],
    country: 'IT',
    state: 'LAZ',
    suburb: 'ROME',
    localArea: 'TRA',
    category: 'Home-cooked meal',
    duration: '3 hours',
    maxGuests: 6,
    pricePerGuest: 85,
    mainImageId: 'exp-1-main',
    thumbnailImageIds: ['exp-1-thumb-1', 'exp-1-thumb-2'],
    description: 'Join me in my charming Trastevere home for a journey through Roman cuisine. We\'ll start with classic antipasti, then I\'ll teach you the art of making fresh pasta, just like my nonna taught me. We\'ll finish with a delicious homemade tiramisu and stories of old Rome.',
    menu: {
      description: 'A 4-course traditional Roman meal.',
      cuisine: 'Italian',
      dietary: ['Vegetarian option available'],
      spiceLevel: 'Mild',
    },
    rating: 4.9,
    reviewCount: 134,
    reviews: [reviews[0]],
    availability: ['Wednesday', 'Friday', 'Saturday'],
    houseRules: { pets: true, smoking: false },
  },
  {
    id: '2',
    title: 'Oaxacan Street Taco Fiesta',
    host: hosts[3],
    country: 'MX',
    state: 'MEX',
    suburb: 'MEXCITY',
    localArea: 'CON',
    category: 'Cultural dinner',
    duration: '2.5 hours',
    maxGuests: 8,
    pricePerGuest: 60,
    mainImageId: 'exp-2-main',
    thumbnailImageIds: [],
    description: 'Experience the soul of Oaxacan street food without leaving my cozy kitchen. We\'ll explore different types of masa, craft a variety of fillings from cochinita pibil to fresh fish, and mix up some zesty salsas. Come hungry and ready for a fiesta!',
    menu: {
      description: 'Taco tasting menu with appetizers and dessert.',
      cuisine: 'Mexican',
      dietary: ['Gluten-Free', 'Vegan option available'],
      spiceLevel: 'Medium',
    },
    rating: 4.8,
    reviewCount: 98,
    reviews: [],
    availability: ['Tuesday', 'Thursday', 'Saturday'],
    houseRules: { pets: false, smoking: true },
  },
  {
    id: '3',
    title: 'Zen & Simplicity: A Japanese Meal',
    host: hosts[1],
    country: 'JP',
    state: 'KYO',
    suburb: 'KYOTO',
    localArea: 'GION',
    category: 'Home-cooked meal',
    duration: '2 hours',
    maxGuests: 4,
    pricePerGuest: 120,
    mainImageId: 'exp-3-main',
    thumbnailImageIds: [],
    description: 'Discover "washoku," the Japanese philosophy of food that emphasizes balance and harmony. In my minimalist home, we will enjoy a simple, elegant meal that highlights the natural flavors of seasonal ingredients. This is a quiet, contemplative experience.',
    menu: {
      description: 'A traditional multi-course "ichiju sansai" meal.',
      cuisine: 'Japanese',
      dietary: [],
      spiceLevel: 'Mild',
    },
    rating: 4.9,
    reviewCount: 72,
    reviews: [reviews[1]],
    availability: ['Monday', 'Friday'],
    houseRules: { pets: false, smoking: false },
  },
  {
    id: '4',
    title: 'South Indian Family Feast',
    host: hosts[2],
    country: 'IN',
    state: 'KAR',
    suburb: 'BANG',
    localArea: 'MALL',
    category: 'Cooking + dining',
    duration: '3.5 hours',
    maxGuests: 8,
    pricePerGuest: 55,
    mainImageId: 'exp-4-main',
    thumbnailImageIds: [],
    description: 'Welcome to our home! My mother and I will guide you through the vibrant flavors of our Tamil heritage. You\'ll learn to make crispy dosas, fluffy idlis, and a variety of chutneys and sambar. It\'s a hands-on, joyful, and delicious celebration.',
    menu: {
      description: 'An elaborate South Indian tiffin, served on a banana leaf.',
      cuisine: 'Indian',
      dietary: ['Vegetarian', 'Vegan'],
      spiceLevel: 'Spicy',
    },
    rating: 4.85,
    reviewCount: 150,
    reviews: [],
    availability: ['Saturday', 'Sunday'],
    houseRules: { pets: false, smoking: false },
  },
];

export const hostApplications: HostApplication[] = [
    {
        id: 'app-1',
        hostName: 'Maria',
        city: 'Rome',
        country: 'Italy',
        experienceTitle: 'Nonna\'s Roman Pasta Feast',
        status: 'Approved',
        submittedDate: '2023-10-01',
        riskFlag: 'Low',
        profile: {
            photoId: 'host-1',
            bio: 'Passionate Italian home cook...',
            languages: ['Italian', 'English'],
            culture: 'Italian',
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Verified' },
        experience: experiences[0],
    },
    {
        id: 'app-2',
        hostName: 'Javier',
        city: 'Mexico City',
        country: 'Mexico',
        experienceTitle: 'Oaxacan Street Taco Fiesta',
        status: 'Pending',
        submittedDate: '2023-10-20',
        riskFlag: 'Low',
        profile: {
            photoId: 'host-4',
            bio: 'From Oaxaca with love...',
            languages: ['Spanish', 'English'],
            culture: 'Mexican',
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Pending' },
        experience: experiences[1],
    },
    {
        id: 'app-3',
        hostName: 'New Host',
        city: 'Paris',
        country: 'France',
        experienceTitle: 'Inappropriate Experience Title',
        status: 'Pending',
        submittedDate: '2023-10-21',
        riskFlag: 'High',
        profile: {
            photoId: 'host-2',
            bio: 'This bio contains bad words.',
            languages: ['French'],
            culture: 'French',
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Verified' },
        experience: { ...experiences[2], title: 'Inappropriate Experience Title' },
    },
    {
        id: 'app-4',
        hostName: 'Kenji',
        city: 'Kyoto',
        country: 'Japan',
        experienceTitle: 'Zen & Simplicity: A Japanese Meal',
        status: 'Changes Needed',
        submittedDate: '2023-10-18',
        riskFlag: null,
        profile: {
            photoId: 'host-2',
            bio: 'I am a designer and a foodie from Tokyo.',
            languages: ['Japanese', 'English'],
            culture: 'Japanese',
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Verified' },
        experience: experiences[2],
    }
];
