
import type { Host, Review, Experience, HostApplication, User, ExperienceReview, Report } from '@/lib/types';

export const users: User[] = [
  {
    id: 'user-1',
    role: 'host',
    fullName: 'Maria',
    email: 'maria@go2culture.com',
    status: 'active',
    createdAt: '2023-01-10T09:00:00Z',
    updatedAt: '2023-01-10T09:00:00Z',
    profilePhotoId: 'host-1'
  },
  {
    id: 'user-2',
    role: 'host',
    fullName: 'Kenji',
    email: 'kenji@go2culture.com',
    status: 'active',
    createdAt: '2023-02-15T09:00:00Z',
    updatedAt: '2023-02-15T09:00:00Z',
    profilePhotoId: 'host-2'
  },
    {
    id: 'user-3',
    role: 'host',
    fullName: 'Priya',
    email: 'priya@go2culture.com',
    status: 'active',
    createdAt: '2023-03-20T09:00:00Z',
    updatedAt: '2023-03-20T09:00:00Z',
    profilePhotoId: 'host-3'
  },
  {
    id: 'user-4',
    role: 'host',
    fullName: 'Javier',
    email: 'javier@go2culture.com',
    status: 'active',
    createdAt: '2023-04-01T09:00:00Z',
    updatedAt: '2023-04-01T09:00:00Z',
    profilePhotoId: 'host-4'
  },
  {
    id: 'user-5',
    role: 'guest',
    fullName: 'Sophie',
    email: 'sophie@guest.com',
    status: 'active',
    createdAt: '2023-10-01T12:00:00Z',
    updatedAt: '2023-10-01T12:00:00Z',
    profilePhotoId: 'guest-1'
  },
  {
    id: 'user-6',
    role: 'guest',
    fullName: 'David',
    email: 'david@guest.com',
    status: 'suspended',
    createdAt: '2023-10-02T14:00:00Z',
    updatedAt: '2023-11-01T10:00:00Z',
    profilePhotoId: 'guest-2'
  },
   {
    id: 'user-7',
    role: 'both',
    fullName: 'Chloe',
    email: 'chloe@go2culture.com',
    status: 'active',
    createdAt: '2023-05-18T11:00:00Z',
    updatedAt: '2023-05-18T11:00:00Z',
    profilePhotoId: 'host-3'
  },
  {
    id: 'user-8',
    role: 'guest',
    fullName: 'Ben',
    email: 'ben@guest.com',
    status: 'active',
    createdAt: '2023-09-05T18:00:00Z',
    updatedAt: '2023-09-05T18:00:00Z',
    profilePhotoId: 'guest-3'
  }
];

export const hosts: Host[] = [
  {
    id: 'host-1',
    userId: 'user-1',
    name: 'Maria',
    avatarImageId: 'host-1',
    status: 'approved',
    profile: {
      bio: 'Passionate Italian home cook, sharing my grandmother\'s recipes with the world. I love opera, fresh pasta, and good conversation.',
      languages: ['Italian', 'English'],
      culturalBackground: 'Italian',
      hostingStyles: ['Family-style', 'Storytelling'],
    },
    verification: { idVerified: true, selfieVerified: true, verifiedAt: '2023-01-10T10:00:00Z' },
    location: { country: 'IT', state: 'LAZ', suburb: 'Rome', localArea: 'Trastevere', postcode: '00153' },
    homeSetup: { homeType: 'Apartment', seating: 'Table', maxGuests: 6, pets: true, smoking: false, accessibility: 'Elevator access' },
    compliance: { guidelinesAccepted: true },
    rating: { average: 4.9, count: 134 },
    createdAt: '2023-01-10T09:00:00Z',
  },
  {
    id: 'host-2',
    userId: 'user-2',
    name: 'Kenji',
    avatarImageId: 'host-2',
    status: 'approved',
    profile: {
      bio: 'I am a designer and a foodie from Tokyo. Join me for a quiet, traditional meal where we can appreciate the beauty of simplicity in Japanese cuisine.',
      languages: ['Japanese', 'English'],
      culturalBackground: 'Japanese',
      hostingStyles: ['Quiet & traditional'],
    },
    verification: { idVerified: true, selfieVerified: true, verifiedAt: '2023-02-15T10:00:00Z' },
    location: { country: 'JP', state: 'KYO', suburb: 'Kyoto', localArea: 'Gion', postcode: '605-0074' },
    homeSetup: { homeType: 'House', seating: 'Floor', maxGuests: 4, pets: false, smoking: false, accessibility: 'One step to enter' },
    compliance: { guidelinesAccepted: true },
    rating: { average: 4.9, count: 72 },
    createdAt: '2023-02-15T09:00:00Z',
  },
   {
    id: 'host-3',
    userId: 'user-3',
    name: 'Priya',
    avatarImageId: 'host-3',
    status: 'approved',
    profile: {
      bio: 'My family and I love to host! We fill our home with the aromas of South Indian spices and the sounds of laughter. Come as a guest, leave as family.',
      languages: ['Tamil', 'English'],
      culturalBackground: 'South Indian',
      hostingStyles: ['Festive & social', 'Family-style'],
    },
    verification: { idVerified: true, selfieVerified: true, verifiedAt: '2023-03-20T10:00:00Z' },
    location: { country: 'IN', state: 'KAR', suburb: 'Bangalore', localArea: 'Malleswaram', postcode: '560003' },
    homeSetup: { homeType: 'House', seating: 'Mixed', maxGuests: 8, pets: false, smoking: false, accessibility: 'Ground floor' },
    compliance: { guidelinesAccepted: true },
    rating: { average: 4.85, count: 150 },
    createdAt: '2023-03-20T09:00:00Z',
  },
  {
    id: 'host-4',
    userId: 'user-4',
    name: 'Javier',
    avatarImageId: 'host-4',
    status: 'approved',
    profile: {
      bio: 'From Oaxaca with love. I bring the vibrant street food culture of Mexico to my home. Expect bold flavors, lots of color, and great stories.',
      languages: ['Spanish', 'English'],
      culturalBackground: 'Mexican',
      hostingStyles: ['Festive & social', 'Storytelling'],
    },
    verification: { idVerified: true, selfieVerified: true, verifiedAt: '2023-04-01T10:00:00Z' },
    location: { country: 'MX', state: 'MEX', suburb: 'Mexico City', localArea: 'La Condesa', postcode: '06140' },
    homeSetup: { homeType: 'Apartment', seating: 'Table', maxGuests: 8, pets: false, smoking: true, accessibility: 'Ramp available' },
    compliance: { guidelinesAccepted: true },
    rating: { average: 4.8, count: 98 },
    createdAt: '2023-04-01T09:00:00Z',
  },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    bookingId: 'booking-1',
    experienceId: '1',
    hostId: 'host-1',
    userId: 'user-5',
    rating: 5,
    comment: 'An absolutely unforgettable evening! Maria\'s pasta was the best I\'ve ever had, and her stories made the experience so special. Felt like dinner with family.',
    createdAt: '2023-10-15T21:00:00Z',
  },
  {
    id: 'review-2',
    bookingId: 'booking-2',
    experienceId: '3',
    hostId: 'host-2',
    userId: 'user-6',
    rating: 5,
    comment: 'The food was incredible, and the atmosphere was so peaceful. A truly authentic and meditative dining experience. Highly recommended.',
    createdAt: '2023-10-12T20:00:00Z',
  },
];

const experienceReviews: Record<string, ExperienceReview[]> = {
  '1': [
    {
      id: 'review-1',
      author: { name: 'Sophie', avatarImageId: 'guest-1' },
      rating: 5,
      comment: 'An absolutely unforgettable evening! Maria\'s pasta was the best I\'ve ever had, and her stories made the experience so special. Felt like dinner with family.',
      date: '2023-10-15',
    },
    {
      id: 'review-3',
      author: { name: 'Alex', avatarImageId: 'guest-2' },
      rating: 5,
      comment: 'Maria is a gem. So welcoming and warm. The food was divine. A must-do in Rome!',
      date: '2023-09-20',
    }
  ],
  '2': [
    {
      id: 'review-4',
      author: { name: 'Chloe', avatarImageId: 'host-3' },
      rating: 5,
      comment: 'The best tacos of my life. Javier has a real passion for his culture and food that shines through. Fun, vibrant, and delicious.',
      date: '2023-11-05',
    },
  ],
  '3': [
     {
      id: 'review-2',
      author: { name: 'David', avatarImageId: 'guest-2' },
      rating: 5,
      comment: 'The food was incredible, and the atmosphere was so peaceful. A truly authentic and meditative dining experience. Highly recommended.',
      date: '2023-10-12',
    },
  ],
  '4': [],
}

export const experiences: Experience[] = [
  {
    id: '1',
    hostId: 'host-1',
    host: hosts.find(h => h.id === 'host-1')!,
    title: 'Nonna\'s Roman Pasta Feast',
    category: 'Home-cooked meal',
    description: 'Join me in my charming Trastevere home for a journey through Roman cuisine. We\'ll start with classic antipasti, then I\'ll teach you the art of making fresh pasta, just like my nonna taught me. We\'ll finish with a delicious homemade tiramisu and stories of old Rome.',
    durationMinutes: 180,
    menu: {
      cuisine: 'Italian',
      description: 'A 4-course traditional Roman meal.',
      dietary: ['Vegetarian option available'],
      spiceLevel: 'Mild',
    },
    pricing: { pricePerGuest: 85, maxGuests: 6 },
    availability: { days: ['Wednesday', 'Friday', 'Saturday'], timeSlots: ['19:00', '20:00'] },
    location: { country: 'IT', state: 'LAZ', suburb: 'ROME', localArea: 'TRA' },
    photos: { mainImageId: 'exp-1-main', thumbnailImageIds: ['exp-1-thumb-1', 'exp-1-thumb-2'] },
    status: 'live',
    rating: { average: 4.9, count: 134 },
    reviews: experienceReviews['1'],
    createdAt: '2023-01-12T09:00:00Z',
  },
  {
    id: '2',
    hostId: 'host-4',
    host: hosts.find(h => h.id === 'host-4')!,
    title: 'Oaxacan Street Taco Fiesta',
    category: 'Cultural dinner',
    description: 'Experience the soul of Oaxacan street food without leaving my cozy kitchen. We\'ll explore different types of masa, craft a variety of fillings from cochinita pibil to fresh fish, and mix up some zesty salsas. Come hungry and ready for a fiesta!',
    durationMinutes: 150,
    menu: {
      cuisine: 'Mexican',
      description: 'Taco tasting menu with appetizers and dessert.',
      dietary: ['Gluten-Free', 'Vegan option available'],
      spiceLevel: 'Medium',
    },
    pricing: { pricePerGuest: 60, maxGuests: 8 },
    availability: { days: ['Tuesday', 'Thursday', 'Saturday'], timeSlots: ['18:00', '19:30'] },
    location: { country: 'MX', state: 'MEX', suburb: 'MEXCITY', localArea: 'CON' },
    photos: { mainImageId: 'exp-2-main', thumbnailImageIds: [] },
    status: 'live',
    rating: { average: 4.8, count: 98 },
    reviews: experienceReviews['2'],
    createdAt: '2023-04-02T09:00:00Z',
  },
  {
    id: '3',
    hostId: 'host-2',
    host: hosts.find(h => h.id === 'host-2')!,
    title: 'Zen & Simplicity: A Japanese Meal',
    category: 'Home-cooked meal',
    description: 'Discover "washoku," the Japanese philosophy of food that emphasizes balance and harmony. In my minimalist home, we will enjoy a simple, elegant meal that highlights the natural flavors of seasonal ingredients. This is a quiet, contemplative experience.',
    durationMinutes: 120,
    menu: {
      cuisine: 'Japanese',
      description: 'A traditional multi-course "ichiju sansai" meal.',
      dietary: [],
      spiceLevel: 'Mild',
    },
    pricing: { pricePerGuest: 120, maxGuests: 4 },
    availability: { days: ['Monday', 'Friday'], timeSlots: ['19:00'] },
    location: { country: 'JP', state: 'KYO', suburb: 'KYOTO', localArea: 'GION' },
    photos: { mainImageId: 'exp-3-main', thumbnailImageIds: [] },
    status: 'live',
    rating: { average: 4.9, count: 72 },
    reviews: experienceReviews['3'],
    createdAt: '2023-02-16T09:00:00Z',
  },
  {
    id: '4',
    hostId: 'host-3',
    host: hosts.find(h => h.id === 'host-3')!,
    title: 'South Indian Family Feast',
    category: 'Cooking + dining',
    description: 'Welcome to our home! My mother and I will guide you through the vibrant flavors of our Tamil heritage. You\'ll learn to make crispy dosas, fluffy idlis, and a variety of chutneys and sambar. It\'s a hands-on, joyful, and delicious celebration.',
    durationMinutes: 210,
    menu: {
      cuisine: 'Indian',
      description: 'An elaborate South Indian tiffin, served on a banana leaf.',
      dietary: ['Vegetarian', 'Vegan'],
      spiceLevel: 'Spicy',
    },
    pricing: { pricePerGuest: 55, maxGuests: 8 },
    availability: { days: ['Saturday', 'Sunday'], timeSlots: ['12:00', '19:00'] },
    location: { country: 'IN', state: 'KAR', suburb: 'BANG', localArea: 'MALL' },
    photos: { mainImageId: 'exp-4-main', thumbnailImageIds: [] },
    status: 'live',
    rating: { average: 4.85, count: 150 },
    reviews: experienceReviews['4'],
    createdAt: '2023-03-21T09:00:00Z',
  },
];

export const hostApplications: HostApplication[] = [
    {
        id: 'app-1',
        hostName: 'Maria',
        submittedDate: '2023-10-01',
        status: 'Approved',
        riskFlag: 'Low',
        profile: {
            photoId: 'host-1',
            bio: 'Passionate Italian home cook...',
            languages: ['Italian', 'English'],
            culturalBackground: 'Italian',
            hostingStyles: ['Family-style', 'Storytelling'],
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Verified' },
        location: { country: 'IT', state: 'LAZ', suburb: 'Rome', postcode: '00153' },
        homeSetup: { homeType: 'Apartment', seating: 'Table', accessibility: 'Elevator available', maxGuests: 6, pets: false, smoking: false },
        experience: {
            title: 'Nonna\'s Roman Pasta Feast',
            description: experiences[0].description,
            duration: '3 hours',
            category: experiences[0].category,
            menu: {
              cuisine: 'Italian',
              description: 'A 4-course traditional Roman meal.',
              spiceLevel: 'Mild',
            },
            pricing: experiences[0].pricing,
            photos: { mainImageId: experiences[0].photos.mainImageId },
        },
        compliance: { foodBusinessRegistered: true, councilName: 'City of Rome', foodSafetyTrainingCompleted: true, guidelinesAccepted: true, agreeToFoodSafety: true },
    },
    {
        id: 'app-2',
        hostName: 'Javier',
        submittedDate: '2023-10-20',
        status: 'Pending',
        riskFlag: 'Low',
        profile: {
            photoId: 'host-4',
            bio: 'From Oaxaca with love...',
            languages: ['Spanish', 'English'],
            culturalBackground: 'Mexican',
            hostingStyles: ['Festive & social', 'Storytelling'],
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Pending' },
        location: { country: 'MX', state: 'MEX', suburb: 'Mexico City', postcode: '06140' },
        homeSetup: { homeType: 'Apartment', seating: 'Table', pets: true, smoking: true, maxGuests: 8 },
        experience: {
            title: 'Oaxacan Street Taco Fiesta',
            description: experiences[1].description,
            duration: '2.5 hours',
            category: experiences[1].category,
            menu: {
              cuisine: 'Mexican',
              description: 'Taco tasting menu with appetizers and dessert.',
              spiceLevel: 'Medium',
            },
            pricing: experiences[1].pricing,
            photos: { mainImageId: experiences[1].photos.mainImageId },
        },
        compliance: { foodBusinessRegistered: false, foodSafetyTrainingCompleted: true, guidelinesAccepted: true, agreeToFoodSafety: true },
    },
     {
        id: 'app-3',
        hostName: 'Siti',
        submittedDate: '2023-11-05',
        status: 'Changes Needed',
        riskFlag: 'Medium',
        profile: {
            photoId: 'guest-1', // placeholder
            bio: 'I love sharing the diverse flavors of Malaysia with new friends.',
            languages: ['Malay', 'English'],
            culturalBackground: 'Malaysian',
            hostingStyles: ['Family-style'],
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Failed' },
        location: { country: 'MY', state: 'KUL', suburb: 'Kuala Lumpur', postcode: '50450' },
        homeSetup: { homeType: 'Apartment', seating: 'Table', pets: false, smoking: false, maxGuests: 4 },
        experience: {
            title: 'Malaysian Nasi Lemak Lunch',
            description: "Learn to make Malaysia's national dish, Nasi Lemak, with all its delicious accompaniments like sambal, fried chicken, and crispy anchovies.",
            duration: '3 hours',
            category: 'Cooking + dining',
            menu: {
              cuisine: 'Malaysian',
              description: 'Full Nasi Lemak set with teh tarik.',
              spiceLevel: 'Spicy',
            },
            pricing: { pricePerGuest: 45, maxGuests: 4 },
            photos: { mainImageId: 'exp-4-main' }, // placeholder
        },
        compliance: { guidelinesAccepted: true, agreeToFoodSafety: true },
    },
    {
        id: 'app-4',
        hostName: 'Ahmad',
        submittedDate: '2023-11-12',
        status: 'Rejected',
        riskFlag: 'High',
        profile: {
            photoId: 'guest-3', // placeholder
            bio: 'Taste of the desert.',
            languages: ['Arabic'],
            culturalBackground: 'Bedouin',
            hostingStyles: ['Quiet & traditional'],
        },
        verification: { idDocId: 'admin-id', selfieId: 'admin-selfie', status: 'Pending' },
        location: { country: 'JO', suburb: 'Wadi Rum' },
        homeSetup: { homeType: 'Other', seating: 'Floor', maxGuests: 10 },
        experience: {
            title: 'Desert Camp Dinner',
            description: "Dinner under the stars.",
            duration: '4 hours',
            category: 'Cultural dinner',
            menu: {
              cuisine: 'Middle Eastern',
              description: 'Zarb (underground BBQ).',
              spiceLevel: 'Mild',
            },
            pricing: { pricePerGuest: 70, maxGuests: 10 },
            photos: { mainImageId: 'exp-1-main' }, // placeholder
        },
        compliance: { guidelinesAccepted: false, agreeToFoodSafety: false },
    },
];

export const reports: Report[] = [
    {
        id: 'rep-1',
        targetType: 'Review',
        targetId: 'review-1',
        reason: 'Inappropriate content in review comment.',
        reportedBy: 'Maria (Host)',
        reportedUserLink: '/admin/users/user-1',
        date: '2023-11-10T14:00:00Z',
        status: 'Open',
    },
    {
        id: 'rep-2',
        targetType: 'Experience',
        targetId: '4',
        reason: 'Host was unresponsive after booking.',
        reportedBy: 'Sophie (Guest)',
        reportedUserLink: '/admin/users/user-5',
        date: '2023-11-08T10:30:00Z',
        status: 'In Progress',
    },
    {
        id: 'rep-3',
        targetType: 'User',
        targetId: 'user-6',
        reason: 'Suspicious activity on user account.',
        reportedBy: 'System Flag',
        reportedUserLink: null,
        date: '2023-11-05T22:00:00Z',
        status: 'Resolved',
    }
];
