
export const countries = [
  { id: 'AU', name: 'Australia' },
  { id: 'NZ', name: 'New Zealand' },
  { id: 'US', name: 'United States' },
  { id: 'CA', name: 'Canada' },
  { id: 'GB', name: 'United Kingdom' },
  { id: 'AF', name: 'Afghanistan' },
  { id: 'AL', name: 'Albania' },
  { id: 'DZ', name: 'Algeria' },
  { id: 'AS', name: 'American Samoa' },
  { id: 'AD', name: 'Andorra' },
  { id: 'AO', name: 'Angola' },
  { id: 'AI', name: 'Anguilla' },
  { id: 'AQ', name: 'Antarctica' },
  { id: 'AG', name: 'Antigua and Barbuda' },
  { id: 'AR', name: 'Argentina' },
  { id: 'AM', name: 'Armenia' },
  { id: 'AW', name: 'Aruba' },
  { id: 'AT', name: 'Austria' },
  { id: 'AZ', name: 'Azerbaijan' },
  { id: 'BS', name: 'Bahamas' },
  { id: 'BH', name: 'Bahrain' },
  { id: 'BD', name: 'Bangladesh' },
  { id: 'BB', name: 'Barbados' },
  { id: 'BY', name: 'Belarus' },
  { id: 'BE', name: 'Belgium' },
  { id: 'BZ', name: 'Belize' },
  { id: 'BJ', name: 'Benin' },
  { id: 'BM', name: 'Bermuda' },
  { id: 'BT', name: 'Bhutan' },
  { id: 'BO', name: 'Bolivia' },
  { id: 'BA', name: 'Bosnia and Herzegovina' },
  { id: 'BW', name: 'Botswana' },
  { id: 'BR', name: 'Brazil' },
  { id: 'IO', name: 'British Indian Ocean Territory' },
  { id: 'BN', name: 'Brunei Darussalam' },
  { id: 'BG', name: 'Bulgaria' },
  { id: 'BF', name: 'Burkina Faso' },
  { id: 'BI', name: 'Burundi' },
  { id: 'KH', name: 'Cambodia' },
  { id: 'CM', name: 'Cameroon' },
  { id: 'CV', name: 'Cape Verde' },
  { id: 'KY', name: 'Cayman Islands' },
  { id: 'CF', name: 'Central African Republic' },
  { id: 'TD', name: 'Chad' },
  { id: 'CL', name: 'Chile' },
  { id: 'CN', name: 'China' },
  { id: 'CO', name: 'Colombia' },
  { id: 'KM', name: 'Comoros' },
  { id: 'CG', name: 'Congo' },
  { id: 'CD', name: 'Congo, the Democratic Republic of the' },
  { id: 'CK', name: 'Cook Islands' },
  { id: 'CR', name: 'Costa Rica' },
  { id: 'CI', name: 'Cote D\'Ivoire' },
  { id: 'HR', name: 'Croatia' },
  { id: 'CU', name: 'Cuba' },
  { id: 'CY', name: 'Cyprus' },
  { id: 'CZ', name: 'Czech Republic' },
  { id: 'DK', name: 'Denmark' },
  { id: 'DJ', name: 'Djibouti' },
  { id: 'DM', name: 'Dominica' },
  { id: 'DO', name: 'Dominican Republic' },
  { id: 'EC', name: 'Ecuador' },
  { id: 'EG', name: 'Egypt' },
  { id: 'SV', name: 'El Salvador' },
  { id: 'GQ', name: 'Equatorial Guinea' },
  { id: 'ER', name: 'Eritrea' },
  { id: 'EE', name: 'Estonia' },
  { id: 'ET', name: 'Ethiopia' },
  { id: 'FK', name: 'Falkland Islands (Malvinas)' },
  { id: 'FO', name: 'Faroe Islands' },
  { id: 'FJ', name: 'Fiji' },
  { id: 'FI', name: 'Finland' },
  { id: 'FR', name: 'France' },
  { id: 'GF', name: 'French Guiana' },
  { id: 'PF', name: 'French Polynesia' },
  { id: 'GA', name: 'Gabon' },
  { id: 'GM', name: 'Gambia' },
  { id: 'GE', name: 'Georgia' },
  { id: 'DE', name: 'Germany' },
  { id: 'GH', name: 'Ghana' },
  { id: 'GI', name: 'Gibraltar' },
  { id: 'GR', name: 'Greece' },
  { id: 'GL', name: 'Greenland' },
  { id: 'GD', name: 'Grenada' },
  { id: 'GP', name: 'Guadeloupe' },
  { id: 'GU', name: 'Guam' },
  { id: 'GT', name: 'Guatemala' },
  { id: 'GN', name: 'Guinea' },
  { id: 'GW', name: 'Guinea-Bissau' },
  { id: 'GY', name: 'Guyana' },
  { id: 'HT', name: 'Haiti' },
  { id: 'HN', name: 'Honduras' },
  { id: 'HK', name: 'Hong Kong' },
  { id: 'HU', name: 'Hungary' },
  { id: 'IS', name: 'Iceland' },
  { id: 'IN', name: 'India' },
  { id: 'ID', name: 'Indonesia' },
  { id: 'IR', name: 'Iran, Islamic Republic of' },
  { id: 'IQ', name: 'Iraq' },
  { id: 'IE', name: 'Ireland' },
  { id: 'IL', name: 'Israel' },
  { id: 'IT', name: 'Italy' },
  { id: 'JM', name: 'Jamaica' },
  { id: 'JP', name: 'Japan' },
  { id: 'JO', name: 'Jordan' },
  { id: 'KZ', name: 'Kazakhstan' },
  { id: 'KE', name: 'Kenya' },
  { id: 'KI', name: 'Kiribati' },
  { id: 'KP', name: 'Korea, Democratic People\'s Republic of' },
  { id: 'KR', name: 'Korea, Republic of' },
  { id: 'KW', name: 'Kuwait' },
  { id: 'KG', name: 'Kyrgyzstan' },
  { id: 'LA', name: 'Lao People\'s Democratic Republic' },
  { id: 'LV', name: 'Latvia' },
  { id: 'LB', name: 'Lebanon' },
  { id: 'LS', name: 'Lesotho' },
  { id: 'LR', name: 'Liberia' },
  { id: 'LY', name: 'Libyan Arab Jamahiriya' },
  { id: 'LI', name: 'Liechtenstein' },
  { id: 'LT', name: 'Lithuania' },
  { id: 'LU', name: 'Luxembourg' },
  { id: 'MO', name: 'Macao' },
  { id: 'MK', name: 'Macedonia, the Former Yugoslav Republic of' },
  { id: 'MG', name: 'Madagascar' },
  { id: 'MW', name: 'Malawi' },
  { id: 'MY', name: 'Malaysia' },
  { id: 'MV', name: 'Maldives' },
  { id: 'ML', name: 'Mali' },
  { id: 'MT', name: 'Malta' },
  { id: 'MH', name: 'Marshall Islands' },
  { id: 'MQ', name: 'Martinique' },
  { id: 'MR', name: 'Mauritania' },
  { id: 'MU', name: 'Mauritius' },
  { id: 'YT', name: 'Mayotte' },
  { id: 'MX', name: 'Mexico' },
  { id: 'FM', name: 'Micronesia, Federated States of' },
  { id: 'MD', name: 'Moldova, Republic of' },
  { id: 'MC', name: 'Monaco' },
  { id: 'MN', name: 'Mongolia' },
  { id: 'MS', name: 'Montserrat' },
  { id: 'MA', name: 'Morocco' },
  { id: 'MZ', name: 'Mozambique' },
  { id: 'MM', name: 'Myanmar' },
  { id: 'NA', name: 'Namibia' },
  { id: 'NR', name: 'Nauru' },
  { id: 'NP', name: 'Nepal' },
  { id: 'NL', name: 'Netherlands' },
  { id: 'AN', name: 'Netherlands Antilles' },
  { id: 'NC', name: 'New Caledonia' },
  { id: 'NI', name: 'Nicaragua' },
  { id: 'NE', name: 'Niger' },
  { id: 'NG', name: 'Nigeria' },
  { id: 'NU', name: 'Niue' },
  { id: 'NF', name: 'Norfolk Island' },
  { id: 'MP', name: 'Northern Mariana Islands' },
  { id: 'NO', name: 'Norway' },
  { id: 'OM', name: 'Oman' },
  { id: 'PK', name: 'Pakistan' },
  { id: 'PW', name: 'Palau' },
  { id: 'PS', name: 'Palestinian Territory, Occupied' },
  { id: 'PA', name: 'Panama' },
  { id: 'PG', name: 'Papua New Guinea' },
  { id: 'PY', name: 'Paraguay' },
  { id: 'PE', name: 'Peru' },
  { id: 'PH', name: 'Philippines' },
  { id: 'PN', name: 'Pitcairn' },
  { id: 'PL', name: 'Poland' },
  { id: 'PT', name: 'Portugal' },
  { id: 'PR', name: 'Puerto Rico' },
  { id: 'QA', name: 'Qatar' },
  { id: 'RE', name: 'Reunion' },
  { id: 'RO', name: 'Romania' },
  { id: 'RU', name: 'Russian Federation' },
  { id: 'RW', name: 'Rwanda' },
  { id: 'SH', name: 'Saint Helena' },
  { id: 'KN', name: 'Saint Kitts and Nevis' },
  { id: 'LC', name: 'Saint Lucia' },
  { id: 'PM', name: 'Saint Pierre and Miquelon' },
  { id: 'VC', name: 'Saint Vincent and the Grenadines' },
  { id: 'WS', name: 'Samoa' },
  { id: 'SM', name: 'San Marino' },
  { id: 'ST', name: 'Sao Tome and Principe' },
  { id: 'SA', name: 'Saudi Arabia' },
  { id: 'SN', name: 'Senegal' },
  { id: 'CS', name: 'Serbia and Montenegro' },
  { id: 'SC', name: 'Seychelles' },
  { id: 'SL', name: 'Sierra Leone' },
  { id: 'SG', name: 'Singapore' },
  { id: 'SK', name: 'Slovakia' },
  { id: 'SI', name: 'Slovenia' },
  { id: 'SB', name: 'Solomon Islands' },
  { id: 'SO', name: 'Somalia' },
  { id: 'ZA', name: 'South Africa' },
  { id: 'LK', name: 'Sri Lanka' },
  { id: 'SD', name: 'Sudan' },
  { id: 'SR', name: 'Suriname' },
  { id: 'SJ', name: 'Svalbard and Jan Mayen' },
  { id: 'SZ', name: 'Swaziland' },
  { id: 'SE', name: 'Sweden' },
  { id: 'CH', name: 'Switzerland' },
  { id: 'SY', name: 'Syrian Arab Republic' },
  { id: 'TW', name: 'Taiwan, Province of China' },
  { id: 'TJ', name: 'Tajikistan' },
  { id: 'TZ', name: 'Tanzania, United Republic of' },
  { id: 'TH', name: 'Thailand' },
  { id: 'TG', name: 'Togo' },
  { id: 'TK', name: 'Tokelau' },
  { id: 'TO', name: 'Tonga' },
  { id: 'TT', name: 'Trinidad and Tobago' },
  { id: 'TN', name: 'Tunisia' },
  { id: 'TR', name: 'Turkey' },
  { id: 'TM', name: 'Turkmenistan' },
  { id: 'TC', name: 'Turks and Caicos Islands' },
  { id: 'TV', name: 'Tuvalu' },
  { id: 'UG', name: 'Uganda' },
  { id: 'UA', name: 'Ukraine' },
  { id: 'AE', name: 'United Arab Emirates' },
  { id: 'UY', name: 'Uruguay' },
  { id: 'UZ', name: 'Uzbekistan' },
  { id: 'VU', name: 'Vanuatu' },
  { id: 'VE', name: 'Venezuela' },
  { id: 'VN', name: 'Viet Nam' },
  { id: 'VG', name: 'Virgin Islands, British' },
  { id: 'VI', name: 'Virgin Islands, U.s.' },
  { id: 'WF', name: 'Wallis and Futuna' },
  { id: 'EH', name: 'Western Sahara' },
  { id: 'YE', name: 'Yemen' },
  { id: 'ZM', name: 'Zambia' },
  { id: 'ZW', name: 'Zimbabwe' },
];

export const regions = [
  // Australia
  { id: 'NSW', name: 'New South Wales', countryId: 'AU' },
  { id: 'VIC', name: 'Victoria', countryId: 'AU' },
  { id: 'QLD', name: 'Queensland', countryId: 'AU' },
  { id: 'SA', name: 'South Australia', countryId: 'AU' },
  { id: 'WA', name: 'Western Australia', countryId: 'AU' },
  { id: 'TAS', name: 'Tasmania', countryId: 'AU' },
  { id: 'ACT', name: 'Australian Capital Territory', countryId: 'AU' },
  { id: 'NT', name: 'Northern Territory', countryId: 'AU' },

  // New Zealand
  { id: 'AUK', name: 'Auckland', countryId: 'NZ' },
  { id: 'WGN', name: 'Wellington', countryId: 'NZ' },
  { id: 'CAN', name: 'Canterbury', countryId: 'NZ' },
  { id: 'OTA', name: 'Otago', countryId: 'NZ' },
  { id: 'WKO', name: 'Waikato', countryId: 'NZ' },
  { id: 'BOP', name: 'Bay of Plenty', countryId: 'NZ' },
  
  // United States
  { id: 'CA', name: 'California', countryId: 'US' },
  { id: 'NY', name: 'New York', countryId: 'US' },
  { id: 'TX', name: 'Texas', countryId: 'US' },
  { id: 'FL', name: 'Florida', countryId: 'US' },
  { id: 'IL', name: 'Illinois', countryId: 'US' },

  // Canada
  { id: 'ON', name: 'Ontario', countryId: 'CA' },
  { id: 'QC', name: 'Quebec', countryId: 'CA' },
  { id: 'BC', name: 'British Columbia', countryId: 'CA' },
  { id: 'AB', name: 'Alberta', countryId: 'CA' },
  { id: 'MB', name: 'Manitoba', countryId: 'CA' },

  // United Kingdom
  { id: 'ENG', name: 'England', countryId: 'GB' },
  { id: 'SCT', name: 'Scotland', countryId: 'GB' },
  { id: 'WLS', name: 'Wales', countryId: 'GB' },
  { id: 'NIR', name: 'Northern Ireland', countryId: 'GB' },
];

// Note: In the app's context, "suburbs" are treated as major cities.
export const suburbs = [
  // Australia
  { id: 'SYD', name: 'Sydney', regionId: 'NSW' },
  { id: 'MEL', name: 'Melbourne', regionId: 'VIC' },
  { id: 'BRI', name: 'Brisbane', regionId: 'QLD' },
  { id: 'PER', name: 'Perth', regionId: 'WA' },
  { id: 'ADL', name: 'Adelaide', regionId: 'SA' },
  { id: 'CBR', name: 'Canberra', regionId: 'ACT' },
  { id: 'HBA', name: 'Hobart', regionId: 'TAS' },
  
  // New Zealand
  { id: 'AKL', name: 'Auckland', regionId: 'AUK' },
  { id: 'WLG', name: 'Wellington', regionId: 'WGN' },
  { id: 'CHC', name: 'Christchurch', regionId: 'CAN' },
  { id: 'ZQN', name: 'Queenstown', regionId: 'OTA' },
  { id: 'HLZ', name: 'Hamilton', regionId: 'WKO' },
  { id: 'TRG', name: 'Tauranga', regionId: 'BOP' },
  
  // United States
  { id: 'NYC', name: 'New York City', regionId: 'NY' },
  { id: 'LA', name: 'Los Angeles', regionId: 'CA' },
  { id: 'CHI', name: 'Chicago', regionId: 'IL' },
  { id: 'HOU', name: 'Houston', regionId: 'TX' },
  { id: 'MIA', name: 'Miami', regionId: 'FL' },

  // Canada
  { id: 'TOR', name: 'Toronto', regionId: 'ON' },
  { id: 'MTL', name: 'Montreal', regionId: 'QC' },
  { id: 'VAN', name: 'Vancouver', regionId: 'BC' },
  { id: 'CAL', name: 'Calgary', regionId: 'AB' },
  { id: 'WPG', name: 'Winnipeg', regionId: 'MB' },

  // United Kingdom
  { id: 'LDN', name: 'London', regionId: 'ENG' },
  { id: 'EDH', name: 'Edinburgh', regionId: 'SCT' },
  { id: 'CDF', name: 'Cardiff', regionId: 'WLS' },
  { id: 'BFS', name: 'Belfast', regionId: 'NIR' },
];

// Note: In the app's context, "localAreas" are the suburbs within a city.
export const localAreas = [
  // Sydney (SYD)
  { id: 'CBD-SYD', name: 'Sydney CBD', suburbId: 'SYD' },
  { id: 'SURRY', name: 'Surry Hills', suburbId: 'SYD' },
  { id: 'BONDI', name: 'Bondi', suburbId: 'SYD' },
  { id: 'NEWTOWN_SYD', name: 'Newtown', suburbId: 'SYD' },
  { id: 'MANLY', name: 'Manly', suburbId: 'SYD' },
  { id: 'HARRISPARK', name: 'Harris Park', suburbId: 'SYD' },
  { id: 'CHATSWOOD', name: 'Chatswood', suburbId: 'SYD' },
  { id: 'PADDINGTON_SYD', name: 'Paddington', suburbId: 'SYD' },
  { id: 'REDFERN', name: 'Redfern', suburbId: 'SYD' },
  { id: 'DARLINGHURST', name: 'Darlinghurst', suburbId: 'SYD' },
  { id: 'THEROCKS', name: 'The Rocks', suburbId: 'SYD' },
  { id: 'COOGEE', name: 'Coogee', suburbId: 'SYD' },
  { id: 'CRONULLA', name: 'Cronulla', suburbId: 'SYD' },
  { id: 'PARRAMATTA', name: 'Parramatta', suburbId: 'SYD' },
  { id: 'LEICHHARDT', name: 'Leichhardt', suburbId: 'SYD' },
  { id: 'MARRICKVILLE', name: 'Marrickville', suburbId: 'SYD' },
  { id: 'BANKSTOWN', name: 'Bankstown', suburbId: 'SYD' },
  { id: 'CABRAMATTA', name: 'Cabramatta', suburbId: 'SYD' },
  { id: 'LAKEMBA', name: 'Lakemba', suburbId: 'SYD' },
  { id: 'CAMPSIE', name: 'Campsie', suburbId: 'SYD' },
  { id: 'BURWOOD', name: 'Burwood', suburbId: 'SYD' },
  { id: 'STRATHFIELD', name: 'Strathfield', suburbId: 'SYD' },
  { id: 'ASHFIELD', name: 'Ashfield', suburbId: 'SYD' },
  { id: 'GLEBE', name: 'Glebe', suburbId: 'SYD' },


  // Melbourne (MEL)
  { id: 'CARLTON', name: 'Carlton', suburbId: 'MEL' },
  { id: 'FITZROY', name: 'Fitzroy', suburbId: 'MEL' },
  { id: 'STKILDA', name: 'St Kilda', suburbId: 'MEL' },
  { id: 'S_YARRA', name: 'South Yarra', suburbId: 'MEL' },
  { id: 'RICHMOND_MEL', name: 'Richmond', suburbId: 'MEL' },
  { id: 'BRUNSWICK', name: 'Brunswick', suburbId: 'MEL' },
  { id: 'COLLINGWOOD', name: 'Collingwood', suburbId: 'MEL' },
  { id: 'PRAHRAN', name: 'Prahran', suburbId: 'MEL' },
  { id: 'SOUTHBANK', name: 'Southbank', suburbId: 'MEL' },
  { id: 'FOOTSCRAY', name: 'Footscray', suburbId: 'MEL' },
  { id: 'COBURG', name: 'Coburg', suburbId: 'MEL' },
  { id: 'BOXHILL', name: 'Box Hill', suburbId: 'MEL' },
  { id: 'DANDENONG', name: 'Dandenong', suburbId: 'MEL' },
  { id: 'SPRINGVALE', name: 'Springvale', suburbId: 'MEL' },
  { id: 'PRESTON', name: 'Preston', suburbId: 'MEL' },
  { id: 'NORTHCOTE', name: 'Northcote', suburbId: 'MEL' },
  { id: 'HAWTHORN', name: 'Hawthorn', suburbId: 'MEL' },

  // Brisbane (BRI)
  { id: 'WESTEND', name: 'West End', suburbId: 'BRI' },
  { id: 'FORTITUDE', name: 'Fortitude Valley', suburbId: 'BRI' },
  { id: 'SOUTHPANK_BRI', name: 'South Bank', suburbId: 'BRI' },
  { id: 'NEWFARM', name: 'New Farm', suburbId: 'BRI' },
  { id: 'PADDINGTON_BRI', name: 'Paddington', suburbId: 'BRI' },
  { id: 'KANGAROOPT', name: 'Kangaroo Point', suburbId: 'BRI' },
  { id: 'TOOWONG', name: 'Toowong', suburbId: 'BRI' },
  { id: 'SUNNYBANK', name: 'Sunnybank', suburbId: 'BRI' },
  { id: 'STONESCORNER', name: 'Stones Corner', suburbId: 'BRI' },
  { id: 'WOOLLOONGABBA', name: 'Woolloongabba', suburbId: 'BRI' },

  // Perth (PER)
  { id: 'FREMANTLE', name: 'Fremantle', suburbId: 'PER' },
  { id: 'NORTHBRIDGE', name: 'Northbridge', suburbId: 'PER' },
  { id: 'SUBIACO', name: 'Subiaco', suburbId: 'PER' },
  { id: 'LEEDERVILLE', name: 'Leederville', suburbId: 'PER' },
  { id: 'COTTESLOE', name: 'Cottesloe', suburbId: 'PER' },
  { id: 'SCARBOROUGH', name: 'Scarborough', suburbId: 'PER' },
  { id: 'MTLAWLEY', name: 'Mount Lawley', suburbId: 'PER' },
  { id: 'VICTORIAPARK', name: 'Victoria Park', suburbId: 'PER' },
  { id: 'EASTPERTH', name: 'East Perth', suburbId: 'PER' },

  // Adelaide (ADL)
  { id: 'NORTHADL', name: 'North Adelaide', suburbId: 'ADL' },
  { id: 'GLENELG', name: 'Glenelg', suburbId: 'ADL' },
  { id: 'NORWOOD', name: 'Norwood', suburbId: 'ADL' },
  { id: 'HENLEY', name: 'Henley Beach', suburbId: 'ADL' },
  { id: 'PROSPECT', name: 'Prospect', suburbId: 'ADL' },
  { id: 'GOODWOOD', name: 'Goodwood', suburbId: 'ADL' },

  // Canberra (CBR)
  { id: 'BRADDON', name: 'Braddon', suburbId: 'CBR' },
  { id: 'KINGSTON', name: 'Kingston', suburbId: 'CBR' },
  { id: 'MANUKA', name: 'Manuka', suburbId: 'CBR' },
  { id: 'DICKSON', name: 'Dickson', suburbId: 'CBR' },
  { id: 'CIVIC', name: 'Civic', suburbId: 'CBR' },

  // Hobart (HBA)
  { id: 'BATTERYPT', name: 'Battery Point', suburbId: 'HBA' },
  { id: 'SANDYBAY', name: 'Sandy Bay', suburbId: 'HBA' },
  { id: 'NORTHHBA', name: 'North Hobart', suburbId: 'HBA' },
  { id: 'SALAMANCA', name: 'Salamanca', suburbId: 'HBA' },
  { id: 'MOONAH', name: 'Moonah', suburbId: 'HBA' },

  // Auckland (AKL)
  { id: 'PONSONBY', name: 'Ponsonby', suburbId: 'AKL' },
  { id: 'PARNELL', name: 'Parnell', suburbId: 'AKL' },
  { id: 'NEWMARKET', name: 'Newmarket', suburbId: 'AKL' },
  { id: 'DEVONPORT', name: 'Devonport', suburbId: 'AKL' },
  { id: 'MTEDEN', name: 'Mount Eden', suburbId: 'AKL' },
  { id: 'TAKAPUNA', name: 'Takapuna', suburbId: 'AKL' },
  { id: 'GREYLYNN', name: 'Grey Lynn', suburbId: 'AKL' },
  { id: 'WAIHEKE', name: 'Waiheke Island', suburbId: 'AKL' },
  { id: 'SANDRINGHAM', name: 'Sandringham', suburbId: 'AKL' },
  { id: 'KINGSLAND', name: 'Kingsland', suburbId: 'AKL' },

  // Wellington (WLG)
  { id: 'TEARO', name: 'Te Aro', suburbId: 'WLG' },
  { id: 'MTVICTORIA', name: 'Mount Victoria', suburbId: 'WLG' },
  { id: 'ORIENTALBAY', name: 'Oriental Bay', suburbId: 'WLG' },
  { id: 'KELBURN', name: 'Kelburn', suburbId: 'WLG' },
  { id: 'NEWTOWN_WLG', name: 'Newtown', suburbId: 'WLG' },
  { id: 'MIRAMAR', name: 'Miramar', suburbId: 'WLG' },
  { id: 'PETONE', name: 'Petone', suburbId: 'WLG' },

  // Christchurch (CHC)
  { id: 'RICCARTON', name: 'Riccarton', suburbId: 'CHC' },
  { id: 'MERIVALE', name: 'Merivale', suburbId: 'CHC' },
  { id: 'SUMNER', name: 'Sumner', suburbId: 'CHC' },
  { id: 'LYTTELTON', name: 'Lyttelton', suburbId: 'CHC' },
  { id: 'ADDINGTON', name: 'Addington', suburbId: 'CHC' },

  // Queenstown (ZQN)
  { id: 'FRANKTON', name: 'Frankton', suburbId: 'ZQN' },
  { id: 'ARROWTOWN', name: 'Arrowtown', suburbId: 'ZQN' },
  { id: 'LAKEHAYES', name: 'Lake Hayes', suburbId: 'ZQN' },

  // New York City (NYC)
  { id: 'MANHATTAN', name: 'Manhattan', suburbId: 'NYC' },
  { id: 'BROOKLYN', name: 'Brooklyn', suburbId: 'NYC' },
  { id: 'QUEENS', name: 'Queens', suburbId: 'NYC' },
  { id: 'BRONX', name: 'The Bronx', suburbId: 'NYC' },
  { id: 'STATENISLAND', name: 'Staten Island', suburbId: 'NYC' },

  // Los Angeles (LA)
  { id: 'HOLLYWOOD', name: 'Hollywood', suburbId: 'LA' },
  { id: 'SANTAMONICA', name: 'Santa Monica', suburbId: 'LA' },
  { id: 'BEVERLYHILLS', name: 'Beverly Hills', suburbId: 'LA' },
  { id: 'VENICE', name: 'Venice', suburbId: 'LA' },
  { id: 'DOWNTOWNLA', name: 'Downtown LA', suburbId: 'LA' },

  // Chicago (CHI)
  { id: 'THELOOP', name: 'The Loop', suburbId: 'CHI' },
  { id: 'LINCOLNPARK', name: 'Lincoln Park', suburbId: 'CHI' },
  { id: 'WICKERPARK', name: 'Wicker Park', suburbId: 'CHI' },
  { id: 'RIVERNORTH', name: 'River North', suburbId: 'CHI' },

  // Houston (HOU)
  { id: 'DOWNTOWNHOU', name: 'Downtown', suburbId: 'HOU' },
  { id: 'GALLERIA', name: 'Galleria-Uptown', suburbId: 'HOU' },
  { id: 'MIDTOWNHOU', name: 'Midtown', suburbId: 'HOU' },
  { id: 'MONTROSE', name: 'Montrose', suburbId: 'HOU' },

  // Miami (MIA)
  { id: 'SOUTHBEACH', name: 'South Beach', suburbId: 'MIA' },
  { id: 'WYNWOOD', name: 'Wynwood', suburbId: 'MIA' },
  { id: 'BRICKELL', name: 'Brickell', suburbId: 'MIA' },
  { id: 'LITTLEHAVANA', name: 'Little Havana', suburbId: 'MIA' },

  // Toronto (TOR)
  { id: 'DOWNTOWNTOR', name: 'Downtown', suburbId: 'TOR' },
  { id: 'YORKVILLE', name: 'Yorkville', suburbId: 'TOR' },
  { id: 'THEANNEX', name: 'The Annex', suburbId: 'TOR' },
  { id: 'QUEENWEST', name: 'Queen West', suburbId: 'TOR' },

  // Montreal (MTL)
  { id: 'OLDMTL', name: 'Old Montreal', suburbId: 'MTL' },
  { id: 'LEPLATEAU', name: 'Le Plateau', suburbId: 'MTL' },
  { id: 'MILEEND', name: 'Mile End', suburbId: 'MTL' },
  { id: 'GRIFFINTOWN', name: 'Griffintown', suburbId: 'MTL' },

  // Vancouver (VAN)
  { id: 'GASTOWN', name: 'Gastown', suburbId: 'VAN' },
  { id: 'YALETOWN', name: 'Yaletown', suburbId: 'VAN' },
  { id: 'KITSILANO', name: 'Kitsilano', suburbId: 'VAN' },
  { id: 'MAINSTREET', name: 'Main Street', suburbId: 'VAN' },

  // Calgary (CAL)
  { id: 'BELTLINE', name: 'Beltline', suburbId: 'CAL' },
  { id: 'KENSINGTON', name: 'Kensington', suburbId: 'CAL' },
  { id: 'INGLEWOOD', name: 'Inglewood', suburbId: 'CAL' },
  { id: 'STEPHENAVE', name: 'Stephen Avenue', suburbId: 'CAL' },

  // Winnipeg (WPG)
  { id: 'THEFORKS', name: 'The Forks', suburbId: 'WPG' },
  { id: 'EXCHANGEDIST', name: 'Exchange District', suburbId: 'WPG' },
  { id: 'OSBORNEVILLAGE', name: 'Osborne Village', suburbId: 'WPG' },

  // London (LDN)
  { id: 'SOHO', name: 'Soho', suburbId: 'LDN' },
  { id: 'SHOREDITCH', name: 'Shoreditch', suburbId: 'LDN' },
  { id: 'NOTTINGHILL', name: 'Notting Hill', suburbId: 'LDN' },
  { id: 'COVENTGARDEN', name: 'Covent Garden', suburbId: 'LDN' },
  { id: 'SOUTHKENSINGTON', name: 'South Kensington', suburbId: 'LDN' },

  // Edinburgh (EDH)
  { id: 'OLDTOWN', name: 'Old Town', suburbId: 'EDH' },
  { id: 'NEWTOWNEDH', name: 'New Town', suburbId: 'EDH' },
  { id: 'LEITH', name: 'Leith', suburbId: 'EDH' },
  { id: 'STOCKBRIDGE', name: 'Stockbridge', suburbId: 'EDH' },

  // Cardiff (CDF)
  { id: 'CARDIFFBAY', name: 'Cardiff Bay', suburbId: 'CDF' },
  { id: 'CITYCENTRE', name: 'City Centre', suburbId: 'CDF' },
  { id: 'PONTCANNA', name: 'Pontcanna', suburbId: 'CDF' },

  // Belfast (BFS)
  { id: 'CATHEDRALQTR', name: 'Cathedral Quarter', suburbId: 'BFS' },
  { id: 'TITANICQTR', name: 'Titanic Quarter', suburbId: 'BFS' },
  { id: 'QUEENSQTR', name: 'Queen\'s Quarter', suburbId: 'BFS' },
];
